m51

#
# Module manifest for module 'Wasp'
#
# Generated by: Joel Bennett
#
# Generated on: 3/24/2014
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Wasp.psm1'

# Version number of this module.
ModuleVersion = '2.5.0.0'

# ID used to uniquely identify this module
GUID = '4f6fd93e-42b7-4548-b522-3ad6759aa62a'

# Author of this module
Author = 'Joel Bennett'

# Company or vendor of this module
CompanyName = 'http://HuddledMasses.org'

# Copyright statement for this module
Copyright = 'Copyright (c) 2008-2014, Joel Bennett, released under the Ms-PL'

# Description of the functionality provided by this module
Description = 'A Windows Automation Script module for Powershell'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '2.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = 'chris'

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = '2.0'

# Processor architecture (None, X86, Amd64) required by this module
ProcessorArchitecture = 'None'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @(@{ModuleName = 'Reflection'; ModuleVersion = '4.5'; })

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'UIAutomationClient', 'UIAutomationTypes'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'UIAutomation.Types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'UIAutomation.Format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('WindowsInput.dll')

# Functions to export from this module
FunctionsToExport = 'ConvertTo-DockPattern', 'ConvertTo-ExpandCollapsePattern', 
               'ConvertTo-GridItemPattern', 'ConvertTo-GridPattern', 
               'ConvertTo-InvokePattern', 'ConvertTo-ItemContainerPattern', 
               'ConvertTo-MultipleViewPattern', 'ConvertTo-RangeValuePattern', 
               'ConvertTo-ScrollItemPattern', 'ConvertTo-ScrollPattern', 
               'ConvertTo-SelectionItemPattern', 'ConvertTo-SelectionPattern', 
               'ConvertTo-SynchronizedInputPattern', 'ConvertTo-TextPattern', 
               'ConvertTo-TogglePattern', 'ConvertTo-TransformPattern', 
               'ConvertTo-ValuePattern', 'ConvertTo-VirtualizedItemPattern', 
               'ConvertTo-WindowPattern', 'formatter', 'Get-ClickablePoint', 
               'Get-Text.DocumentRange', 'Get-Text.SupportedTextSelection', 
               'Get-TextAnimationStyle', 'Get-TextBackgroundColor', 
               'Get-TextBulletStyle', 'Get-TextCapStyle', 'Get-TextCulture', 
               'Get-TextFontName', 'Get-TextFontSize', 'Get-TextFontWeight', 
               'Get-TextForegroundColor', 'Get-TextHorizontalTextAlignment', 
               'Get-TextIndentationFirstLine', 'Get-TextIndentationLeading', 
               'Get-TextIndentationTrailing', 'Get-TextIsHidden', 'Get-TextIsItalic', 
               'Get-TextIsReadOnly', 'Get-TextIsSubscript', 'Get-TextIsSuperscript', 
               'Get-TextMarginBottom', 'Get-TextMarginLeading', 'Get-TextMarginTop', 
               'Get-TextMarginTrailing', 'Get-TextOutlineStyles', 
               'Get-TextOverlineColor', 'Get-TextOverlineStyle', 
               'Get-TextStrikethroughColor', 'Get-TextStrikethroughStyle', 
               'Get-TextTabs', 'Get-TextTextFlowDirections', 
               'Get-TextUnderlineColor', 'Get-TextUnderlineStyle', 
               'Invoke-Dock.SetDockPosition', 'Invoke-ExpandCollapse.Collapse', 
               'Invoke-ExpandCollapse.Expand', 'Invoke-Grid.GetItem', 
               'Invoke-Invoke.Invoke', 'Invoke-ItemContainer.FindItemByProperty', 
               'Invoke-MultipleView.GetViewName', 
               'Invoke-MultipleView.SetCurrentView', 'Invoke-RangeValue.SetValue', 
               'Invoke-Scroll.Scroll', 'Invoke-Scroll.ScrollHorizontal', 
               'Invoke-Scroll.ScrollVertical', 'Invoke-Scroll.SetScrollPercent', 
               'Invoke-ScrollItem.ScrollIntoView', 
               'Invoke-SelectionItem.AddToSelection', 
               'Invoke-SelectionItem.RemoveFromSelection', 
               'Invoke-SelectionItem.Select', 'Invoke-SynchronizedInput.Cancel', 
               'Invoke-SynchronizedInput.StartListening', 
               'Invoke-Text.GetSelection', 'Invoke-Text.GetVisibleRanges', 
               'Invoke-Text.RangeFromChild', 'Invoke-Text.RangeFromPoint', 
               'Invoke-Toggle.Toggle', 'Invoke-Transform.Move', 
               'Invoke-Transform.Resize', 'Invoke-Transform.Rotate', 
               'Invoke-Value.SetValue', 'Invoke-VirtualizedItem.Realize', 
               'Invoke-Window.Close', 'Invoke-Window.SetWindowVisualState', 
               'Invoke-Window.WaitForInputIdle', 'Register-InvokeInvoked', 
               'Register-SelectionInvalidated', 
               'Register-SelectionItemElementAddedToSelection', 
               'Register-SelectionItemElementRemovedFromSelection', 
               'Register-SelectionItemElementSelected', 
               'Register-SynchronizedInputInputDiscarded', 
               'Register-SynchronizedInputInputReachedOtherElement', 
               'Register-SynchronizedInputInputReachedTarget', 
               'Register-TextTextChanged', 'Register-TextTextSelectionChanged', 
               'Register-WindowWindowClosed', 'Register-WindowWindowOpened', 
               'Select-UIElement', 'Send-UIKeys', 'Set-UIFocus', 'Set-UIText', 
               'Show-Window'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = 'Invoke-UIElement'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'Wasp.psm1', 'Wasp.psd1', 'WindowsInput.dll', 
               'UIAutomation.Format.ps1xml', 'UIAutomation.Types.ps1xml', 
               'Samples\Notepad++.ps1', 'Samples\UsingAddInput.ps1
	'Get-Service | wasp',	
	'Start-Sleep -Seconds 1,'
## .NET:
'Invoke-[void][reflectionL<STRING>llist=new linkedlist<string>new string[] {..
'Invoke-plan a head focus on a task learn new things]::}loadwithpartialname("system.windows.forms")
'Invoke-[system.windows.forms.sendkeys]::sendwait('^v')
'Invoke-e$mport', 
	locaL: CHAR/WASP DIR; 
	TYPE; add wasp 
STRING =ARAAY [0..MAXSIZE-1] OF CHAR;

PTR=POINTER TO NODE;
NODE=RECORD
	NAME :	STRING;
	LCHILDRCHILD : PTR
IF (T # NIL )THEN 
'Invoke-INORDER(T^.LCHILD)"POINT A"
'Invoke-WRITE (T^.NAME)
INORDER(T^.RCHILD) "PONIT B";

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''



