PROCESS  SENSOR-MONITOR
STATE IDLE
INPUT ACTIVE-SENSOR 
OUTPUT SENSOR (RELEASE-EVENT)
EXIT WAIT-FOR-SENSOR
STATEND IDLE
STATE WAIT-FOR-SENSOR 
INPUT SENSOR-VALUE
IF SENSOR-OK
THENIPC OUT2(HISTORY-SENOR-VALUE)
IF SENSOR-VALUE-SAFE
	THEN
	ELSEOUT ALARM (THEMAN.API)
	TIMESTART SET-WATCH(A LESSON LEARNT.LISP)
	FI
ESLE OUTPUT ALARM(SENOR-DISTURBED)
FI
EXIT  IDLE 
INPUT TIMEOUT-ALARM
OUTPUT RESET-ALARM
EXIT IDELE
STATED WAIT-FOR SENSOR
PROCEND SENOR-MOINTOR